# Literature Review {#sec-literature}

```{r setup, file = "R/chapter_start.R", include = FALSE}
# a number of commands need to run at the beginning of each chapter. This
# includes loading libraries that I always use, as well as options for 
# displaying numbers and text.
library(mlogit)
library(ggnewscale)
```


Equitable access to community resources has been a topic of research and study,
especially when looking at the impacts on measures of well-being and economic
opportunity. Current social issues, economic opportunity and equity are
significant topics that can help us ensure that each population demographic can
have similar opportunities. Equity as a term is being fair and impartial,
different from equality. Equality is providing the exact same thing to all
people, whereas equity would provide different things to different people
because of their circumstances in order to create a fair system. Lower-income
populations frequently sit at a different level of advantage than higher-income
populations, including when looking at accessibility [@grengs2015, @hu2015,
@witten2003]. It is important to discover how different transportation policies
can improve accessibility to create better equity. Creating equitable societies
and equitable transportation policies is important in order to remove any
discrimination already present in the transportation network. In this way states
can decrease the disparity that is common when looking at different
neighborhoods and demographics. Perhaps there are low-income neighborhoods that
do not have the same economic opportunity or resource accessibility as
high-income neighborhoods. If we increase the accessibility of low-income
neighborhoods, could that then increase the quality of life and health for those
neighborhoods as well?

In addition to economic opportunity, the connection between well-being and
opportunity is also significant, discovering who has access to which resources
and how that access corresponds to their health [@cass2005, @ermagun2020,
@handy1997, @schwanen2015]. A subjective sense of positive well-being correlates
with increased access to more community resources: increased access was
specifically connected with variety of resources, not necessarily number of the
same type of resource. This increased access is true for both high- and
low-income populations. However, high-income demographics frequently tend have
better access to a variety of resources because of such variables as available
child care, a transportation source available, or even time available to do
things [@currie2010, @liu2022] . In addition, increased access to resources such
as parks or other greenspace have been found to decrease likelihood of mental
health disorders, as well as improve physical activity [@francis2012,
@madzia2019]. Different age groups each have a different response to access to
greenspace. However, among all age groups there is a positive correlation.In
addition to health impacts, lack of accessibility also affects economic
opportunity when considering access to employment, affordable care, and other
stores and shops [@currie2010, @hu2015].

### Food Deserts and Swamps

While there are many different community resources that can be the center of
study, such as libraries, green space, hospitals, etc., this project will focus
on the resource of grocery stores and discovering any correlation between
accessibility to good nutrition environments such as healthy grocery stores and
the demographic makeup of specific block groups, such as economic bracket and
different ethnic groups. Lack of accessibility to grocery stores can have an
effect on physical health and well-being [@aggarwal2014]. This access is related
directly with consumption of healthy foods, as well as indirectly with perceived
sense of well-being.

Much of the current research that has been done has shown a different level of
accessibility for different demographics, such as low income populations. Low
income populations have been shown to frequently have less access to fresh
fruits and vegetables [@algert2006, @losada-rojas2021]. This may not be directly
correlated to the physical distance from a grocery store, but the store that was
chosen for these demographics. In a study analyzing grocery store choice in
Seattle it was found that in some instances, there is a closer store with better
produce, but for some reason it was not chosen and instead a store that was
further away was chosen that did not have the same quantity and variety of fresh
produce. This was found again in a different study, that frequently people will
travel to a store that is not the closest store for different reasons
[@clifton2004, @hillier2011]. This study will help to determine that choice
pattern and identify which variables are important when choosing a store to help
improve accessibility more than simple distance measures.

However, areas that do not have any full service grocery stores however are also
important to look at, with those areas being known as food swamps. These food
swamps are an idea that there are locations where there is not healthy food
available, so the only option that is readily accessible for food or meals would
be fast food or convenience stores. There have been studies analyzing the
different food swamp areas and what could be done to improve those areas, such
as adding grocery stores or corner markets [@bao2020]. These food swamps are
areas that discriminate between those without readily available transit options
and those with easy access to cars, creating a barrier to equity. In addition,
these food swamp areas are especially significant when looking at the public
health impacts of food accessibility and discovering how we can improve the
quality of food available to those in every demographic to create an equitable
solution to health differences.

Past research done clearly shows that location of store, quality of store, and
price of store all have an impact on choice of grocery store and accessibility
to grocery stores. This impacts the quality of life and overall health and
well-being of individuals and shows the importance of discovering which
variables are most significant in grocery store choice in order to improve
accessibility and equity. What much existing research suffers from, however, is
the wide variety of measures of access and the definitions used to describe a
"grocery store." Certainly convenience stores do not typically provide the same
variety and quality of goods, but simply excluding them from analyses ignores
how many people obtain a large share of their daily and weekly nutrition, for
better or worse. A measure that can incorporate multimodal access to stores as
well as qualitatively describe the stores along a continuous array of measures
is desirable.
