project:
  type: book

# This defines the .qmd files that are in your document
book:
  title: "Equitable Access to Nutrition in Utah"
  author:
    - name: Gregory S. Macfarlane
      orcid: 0000-0003-3999-7584
      email: gregmacfarlane@gmail.com
      affiliations:
        - name: Civil and Construction Engineering Department, Brigham Young University
          address: 430 EB
          city: Provo
          state: UT
          postal-code: 84602
    - name: Emma Stucki
    - name: Myrranda Salmon
    - name: Alisha Redelfs
    - name: Lori Spruance
    # to add additional authors, simply add another -name: tag 
  date: "09/01/2023"
  chapters:
    - index.qmd
    - 02_litreview.qmd
    - 03_methods.qmd
    - 04_estimation.qmd
    - 05_scenarios.qmd
    - 06_conclusion.qmd
    - acknowledgments.qmd
    - references.qmd
  abstract: | 
    Convenient access to high-quality nutrition is a critical element of public
    health as well as an important interface between communities and the transportation
    system. In this research, we seek to construct a detailed picture of the 
    nutrition environment in three communities in Utah, alongside the community
    members' ability to access that environment through multiple transportation
    modes. In doing so we construct a utility-based accessiblity model enabled 
    by modern mobility device data. This model reveals the tradeoffs between the 
    quality and price of goods on one hand and the distance travelled to reach
    them on the other. We then apply this model to a series of potential access
    -improving policies: building a new store, improving an existing store, and
    improving the non-automobile transport network between residents and existing
    stores. The results show that new or improved store locations bring substantially
    higher benefits than improvements to the transportation system, at likely
    lower costs. The report recommends that UDOT work to increase the availaibility
    of community-sized grocery stores in low-access areas, and consider activity-
    based methods of measuring resource access.
  

bibliography: [groceries.bib, packages.bib]
csl: elsevier-harvard-italics.csl

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreport
    include-in-header: 
      - text: |
          \usepackage{rotating}
    fig-pos: 't'
    keep-tex: true
#  elsevier-pdf:
#    journal:
#      name: Transportation Research Part A
#      cite-style: authoryear
#    keep-tex: true
#    top-level-division: section
#    toc: false
  docx:
    reference-doc: custom-reference-doc.docx
    number-sections: false
    toc: true
    toc-depth: 2
editor: visual
