project:
  type: book

# This defines the .qmd files that are in your document
book:
  title: "Where's dinner coming from? A utility-based investigation of access to nutrition in Utah."
  downloads: pdf
  author:
    - name: Gregory S. Macfarlane
      orcid: 0000-0003-3999-7584
      email: gregmacfarlane@byu.edu
      corresponding: yes
      affiliations:
        - id: byucivil
          name: Civil and Construction Engineering Department, Brigham Young University
          city: Provo, Utah USA
          postal-code: 84602
    - name: Emma Stucki
      affiliations: 
        - ref: byucivil 
    - name: Alisha H. Redelfs
      orcid: 0000-0002-3533-6044
      affiliations:
        - id: byupubh
          name: Public Health Department, Brigham Young University
          city: Provo, Utah USA
          postal-code: 84602
    - name: Lori A. Spruance
      orcid: 0000-0003-0254-483X
      affiliations: 
        - ref: byupubh
    # to add additional authors, simply add another -name: tag 
  date: "1/15/2024"
  chapters:
    - index.qmd
    # - 02_litreview.qmd
    - 03_methods.qmd
    - 04_estimation.qmd
    - 05_scenarios.qmd
    - 06_conclusion.qmd
    - acknowledgments.qmd
    - references.qmd
  abstract: | 
    Convenient access to high-quality nutrition is a critical element of public
    health as well as an important interface between communities and the transportation
    system. In this research, we seek to construct a detailed picture of the 
    nutrition environment in three communities in Utah, alongside the community
    members' ability to access that environment through multiple transportation
    modes. In doing so we construct a utility-based accessiblity model enabled 
    by modern mobility device data. This model reveals the tradeoffs between the 
    quality and price of goods on one hand and the distance traveled to reach
    them on the other. We then apply this model to a series of potential 
    access-improving policies: building a new store, improving an existing store, and
    improving the non-automobile transport network between residents and existing
    stores. The results show that new or improved store locations bring substantially
    higher benefits than improvements to the transportation system, at likely
    lower costs. The findings suggest that transportation agencies work to 
    increase the availability
    of community-sized grocery stores in low-access areas, and consider 
    activity-based methods of measuring resource access.
  

bibliography: [groceries.bib, packages.bib]
csl: apa.csl

keywords:
  - Accessibility
  - Utility-based access
  - Access to nutrition
  - Passive location data

execute: 
  cache: true

format:
  html:
    theme: cosmo
    html-math-method: katex
  elsevier-pdf:
    journal:
      name: Journal of Transport and Land Use
      formatting: review
      model: 3p
    cite-method: citeproc
    include-in-header: 
      - preamble.tex
    crossref:
      chapters: false
    keep-tex: true
    top-level-division: section
    toc: false
